-- SQLBook: Code
CREATE TABLE IF NOT EXISTS games
(
    id INTEGER PRIMARY KEY,
    user1id VARCHAR(255) NOT NULL,
    user2id VARCHAR(255) NOT NULL,
    gametime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    FOREIGN KEY (user1id) REFERENCES user(id) ON DELETE CASCADE,
    FOREIGN KEY (user2id) REFERENCES user(id) ON DELETE CASCADE
);