-- SQLBook: Code
CREATE TABLE IF NOT EXISTS games
(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    user1id VARCHAR(255) NOT NULL,
    user2id VARCHAR(255) NOT NULL,
    gametime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user1score INTEGER DEFAULT 0,
    user2score INTEGER DEFAULT 0
);