export const RESPONSE_SUCCESS_CODE = 0;

export const HANDLER_IDS = {
  INITIAL: 0,
  REGISTER: 1,
  LOG_IN: 2,
  MATCH: 3,
  TOWER_BUY: 4,
  TOWER_ATTACK: 5,
  MONSTER_SPAWN: 6,
  BASE_DAMAGE: 7,
  GAME_OVER: 8,
  MONSTER_DEAD: 9,
  UPDATE_STATE: 10,
};
